// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdlf2TlAb_G-3hjmwX8WPmamy0epN7Krw',
    appId: '1:504800055115:web:a0e6adc196a37e129f62ce',
    messagingSenderId: '504800055115',
    projectId: 'complaint-section',
    authDomain: 'complaint-section.firebaseapp.com',
    storageBucket: 'complaint-section.firebasestorage.app',
    measurementId: 'G-0JC4SK4QPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCotA7JH20vXFdauedjqeXI3n6e4Dd3OE0',
    appId: '1:504800055115:android:6493c2ed9fc670ac9f62ce',
    messagingSenderId: '504800055115',
    projectId: 'complaint-section',
    storageBucket: 'complaint-section.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC__cMUFCVxODAug-G9C-0Z7ucYbagNE0U',
    appId: '1:504800055115:ios:3868b504306242949f62ce',
    messagingSenderId: '504800055115',
    projectId: 'complaint-section',
    storageBucket: 'complaint-section.firebasestorage.app',
    iosBundleId: 'com.example.gmailGeminiComponent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC__cMUFCVxODAug-G9C-0Z7ucYbagNE0U',
    appId: '1:504800055115:ios:3868b504306242949f62ce',
    messagingSenderId: '504800055115',
    projectId: 'complaint-section',
    storageBucket: 'complaint-section.firebasestorage.app',
    iosBundleId: 'com.example.gmailGeminiComponent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdlf2TlAb_G-3hjmwX8WPmamy0epN7Krw',
    appId: '1:504800055115:web:879ea54fb3676f9e9f62ce',
    messagingSenderId: '504800055115',
    projectId: 'complaint-section',
    authDomain: 'complaint-section.firebaseapp.com',
    storageBucket: 'complaint-section.firebasestorage.app',
    measurementId: 'G-XLL09E2KVB',
  );
}
